// Copyright (c) 2015-present Mattermost, Inc. All Rights Reserved.
// See LICENSE.txt for license information.

export function printUsage(): void {
    console.log(
        [
            'Usage:',
            '  e2e-ai-agents init [--yes]',
            '  e2e-ai-agents impact --path <app-root> [options]',
            '  e2e-ai-agents plan --path <app-root> [options]',
            '  e2e-ai-agents suggest --path <app-root> [options]',
            '  e2e-ai-agents heal --path <app-root> --traceability-report <json> [options]',
            '  e2e-ai-agents finalize-generated-tests --path <app-root> [options]',
            '  e2e-ai-agents feedback --path <app-root> --feedback-input <json>',
            '  e2e-ai-agents traceability-capture --path <app-root> --traceability-report <json>',
            '  e2e-ai-agents traceability-ingest --path <app-root> --traceability-input <json>',
            '  e2e-ai-agents generate [--scenarios <path|json>] [--max-attempts <n>] [--dry-run]',
            '  e2e-ai-agents analyze --path <app-root> [--tests-root <path>] [--since <ref>] [--generate] [--generate-output <dir>] [--heal] [--heal-report <json>]',
            '  e2e-ai-agents train --path <project-root> [--no-enrich] [--validate] [--since <ref>] [--pr <num>]',
            '  e2e-ai-agents crew --path <app-root> [--crew-workflow <name>]',
            '  e2e-ai-agents gate --path <app-root> --threshold <n> [--since <ref>]',
            '  e2e-ai-agents cost-report [--path <app-root>]',
            '  e2e-ai-agents bootstrap --path <app-root> [options]',
            '  e2e-ai-agents llm-health',
            '',
            'Options:',
            '  --config <path>       Path to e2e-ai-agents.config.json (auto-discovered if present)',
            '  --path <project-root> Path to the project root (scans both frontend and backend)',
            '  --profile <name>     default | mattermost',
            '  --mattermost         Shortcut for --profile mattermost',
            '  --tests-root <path>   Path to tests root (optional)',
            '  --framework <name>    auto | playwright | cypress | selenium',
            '  --patterns <globs>    Comma-separated test patterns',
            '  --flow-patterns <g>   Comma-separated flow discovery patterns',
            '  --flow-exclude <g>    Comma-separated flow exclude patterns',
            '  --flow-catalog <path> Path to flow catalog JSON',
            '  --allow-fallback      Allow impact analysis without diff',
            '  --pipeline            Run Playwright AI pipeline for missing P0/P1 flows',
            '  --pipeline-scenarios  Number of scenarios per flow (default 3)',
            '  --pipeline-output     Output directory for generated tests',
            '  --pipeline-base-url   Base URL for Playwright runs',
            '  --pipeline-browser    Browser: chrome|chromium|firefox|webkit',
            '  --pipeline-headless   Run in headless mode',
            '  --pipeline-headed     Run in headed mode',
            '  --pipeline-project    Playwright project name',
            '  --pipeline-parallel   Enable parallel mode in generator',
            '  --pipeline-dry-run    Do not execute pipeline (report only)',
            '  --pipeline-mcp        Use Playwright MCP server for exploration/healing',
            '  --pipeline-mcp-allow-fallback  Allow non-MCP fallback if official MCP setup fails',
            '  --pipeline-mcp-only   Require MCP for UI exploration (fail if unavailable)',
            '  --pipeline-mcp-timeout-ms <n>  Timeout per MCP CLI invocation in milliseconds',
            '  --pipeline-mcp-retries <n>  Retry count for retryable MCP CLI failures',
            '  --spec <path>         Optional spec PDF for context',
            '  --since <git-ref>     Git ref for impact analysis (default HEAD~1)',
            '  --time <minutes>      Time limit in minutes',
            '  --budget-usd <amount> Max LLM budget in USD',
            '  --budget-tokens <n>   Max LLM tokens',
            '  --llm-provider <name> LLM provider: auto | anthropic | openai | ollama',
            '  --policy-min-confidence <n>   Minimum confidence for targeted suite',
            '  --policy-safe-merge-confidence <n> Confidence needed for safe-to-merge',
            '  --policy-force-full-on-warnings <n> Escalate to full at warning count',
            '  --policy-risky-patterns <globs>     Comma-separated risky file globs',
            '  --policy-enforcement-mode <mode>    advisory | warn | block',
            '  --policy-block-actions <actions>    Comma-separated CI actions to block/warn',
            '  --crew                               Run Crew enrichment and attach insights to plan output',
            '  --crew-workflow <name>               full-qa | quick-check | design-only',
            '  --ci-comment-path <path>            Write CI markdown summary',
            '  --github-output <path>              Write GitHub Actions outputs',
            '  --fail-on-must-add-tests            Exit non-zero on must-add-tests decision',
            '  --feedback-input <path>             Path to recommendation feedback JSON',
            '  --traceability-report <path>        Path to Playwright JSON report for traceability capture',
            '  --traceability-capture-output <path> Output path for generated traceability ingest JSON',
            '  --traceability-coverage-map <path>  Optional coverage map (test<->files) to enrich traceability capture',
            '  --traceability-changed-files <path> Optional changed-files list/JSON fallback for traceability capture',
            '  --traceability-input <path>         Path to traceability ingest JSON payload',
            '  --traceability-min-hits <n>         Minimum signal hits required per file mapping',
            '  --traceability-max-files-per-test <n> Cap max mapped files per test',
            '  --traceability-max-age-days <n>     Drop stale mappings older than N days',
            '  --branch <name>      Optional handoff branch (prefixed with codex/)',
            '  --commit-message <m> Commit message for finalize-generated-tests',
            '  --create-pr          Open PR with gh after commit',
            '  --pr-title <title>   PR title for finalize-generated-tests',
            '  --pr-body <body>     PR body for finalize-generated-tests',
            '  --pr-base <branch>   PR base branch for finalize-generated-tests',
            '                      (auto-heal-pr defaults to base=master)',
            '  --dry-run            Preview actions without mutating git state',
            '  --max-attempts <n>    Max fix attempts per scenario (default: 3)',
            '  --scenarios <path|json>  Scenarios file/JSON for generate command',
            '  --apply               Apply data-testid patches and generate tests',
            '                        (legacy shortcut; prefer approve-and-generate)',
            '  --no-enrich              Disable LLM enrichment (offline mode, train command)',
            '  --validate               Validate manifest against git history (train command)',
            '  --pr <number>            GitHub PR number for validation (requires gh CLI)',
            '  --yes, -y                Non-interactive mode (train command)',
            '  --output <path>          Output path for route-families.json (train command)',
            '  --help                Show help',
        ].join('\n'),
    );
}
